# Generated by Django 5.0 on 2023-12-20 00:31

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtor', '0002_alter_realtor_date_hired_alter_realtor_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sale_type', models.CharField(choices=[('FOR_SALE', 'For Sale'), ('FOR_RENT', 'For Rent')], default='FOR_SALE', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('home_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('CONDO', 'Condo'), ('FARMHOUSE', 'Farmhouse')], default='APARTMENT', max_length=50)),
                ('area', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(upload_to='photos/2023-12-20 00:31:13.362345')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362378')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362397')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362416')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362434')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362451')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362472')),
                ('photo_7', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362499')),
                ('photo_8', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362518')),
                ('photo_9', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362535')),
                ('photo_10', models.ImageField(blank=True, upload_to='photos/2023-12-20 00:31:13.362552')),
                ('listing_date', models.DateField(default=datetime.datetime(2023, 12, 20, 0, 31, 13, 362570))),
                ('is_published', models.BooleanField(default=True)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.realtor')),
            ],
        ),
    ]
