# Generated by Django 5.0 on 2023-12-21 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_alter_realtor_date_hired_alter_realtor_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='date_hired',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 21, 11, 36, 11, 923988)),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='photo',
            field=models.ImageField(upload_to='photos/2023-12-21 11:36:11.923863'),
        ),
    ]
